spring.application.name=yomu-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/yomu
spring.datasource.username=yomu
spring.datasource.password=yomu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true